messages:
    apply_cost_fail: You do not have enough energy to do that.
    cannot_see_actors_in_room: You see glowing eyes in the distance.
    cannot_see_too_dark: It's too dark to see anything!
    died: You feel a rejuvinating rush as you pass through this mortal plane.
    incapacitated: You are incapacitated and will slowly die if not aided.
    level_up: You leveled up!
    look_at_nothing: Nothing is there.
    incapacitated: You are incapacitated and will die soon if not aided.
    move_failed_fighting: You are fighting!
    move_failed_no_room: 'Alas, nothing is there.'
    move_failed_too_tired: You are too tired to move
    recover_from_incapacitation: You suddenly feel a bit better.
    qualifies_for_level: "You qualify to level up!"
